### ISSUE TITLE
debuerreotype-init fails due to 404

### ISSUE THREAD

**Issue by andrewzah** [debuerreotype/debuerreotype#112] opened 2021-07-02 14:07 UTC
Hi, I'm running this command in a docker container with the latest debuerreotype:

```
debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
```
and it always ends this way
```
warning: no apparent 'stretch/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch/main' ...
warning: no apparent 'stretch-security/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian-security/20210701T143549Z
skipping 'stretch-security/main' ...
warning: no apparent 'stretch-updates/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch-updates/main' ...
error: sources.list ended up empty -- something is definitely wrong
The command '/bin/sh -c debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"' returned a non-zero code: 1
```

note that 
```
http://snapshot.debian.org/archive/debian/20210701T143549Z
```
gives a 404, but this doesn't:
```
http://snapshot.debian.org/archive/debian/20210701T143549Z/dists/
```

full log:
```
Sending build context to Docker daemon  31.74kB
Step 1/31 : FROM andrewzah/debian-debuerreotype:2021-07-01 as rootfs-stage
 ---> fd7da112d4d3
Step 2/31 : RUN debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
 ---> Running in b6fa0afb7d1b
I: Target architecture can be executed
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
I: Valid Release signature (key id 067E3C456BAE240ACEE88F6FEF0F382A1A7B6500)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://snapshot.debian.org/archive/debian/20210701T143549Z...
I: Retrieving libacl1 2.2.52-3+b1
I: Validating libacl1 2.2.52-3+b1
I: Retrieving adduser 3.115
I: Validating adduser 3.115
I: Retrieving apt 1.4.10
I: Validating apt 1.4.10
I: Retrieving libapt-pkg5.0 1.4.10
I: Validating libapt-pkg5.0 1.4.10
I: Retrieving libattr1 1:2.4.47-2+b2
I: Validating libattr1 1:2.4.47-2+b2
I: Retrieving libaudit-common 1:2.6.7-2
I: Validating libaudit-common 1:2.6.7-2
I: Retrieving libaudit1 1:2.6.7-2
I: Validating libaudit1 1:2.6.7-2
I: Retrieving base-files 9.9+deb9u13
I: Validating base-files 9.9+deb9u13
I: Retrieving base-passwd 3.5.43
I: Validating base-passwd 3.5.43
I: Retrieving bash 4.4-5
I: Validating bash 4.4-5
I: Retrieving libbz2-1.0 1.0.6-8.1
I: Validating libbz2-1.0 1.0.6-8.1
I: Retrieving libdebconfclient0 0.227
I: Validating libdebconfclient0 0.227
I: Retrieving coreutils 8.26-3
I: Validating coreutils 8.26-3
I: Retrieving dash 0.5.8-2.4
I: Validating dash 0.5.8-2.4
I: Retrieving libdb5.3 5.3.28-12+deb9u1
I: Validating libdb5.3 5.3.28-12+deb9u1
I: Retrieving debconf 1.5.61
I: Validating debconf 1.5.61
I: Retrieving debian-archive-keyring 2017.5+deb9u1
I: Validating debian-archive-keyring 2017.5+deb9u1
I: Retrieving debianutils 4.8.1.1
I: Validating debianutils 4.8.1.1
I: Retrieving diffutils 1:3.5-3
I: Validating diffutils 1:3.5-3
I: Retrieving dpkg 1.18.25
I: Validating dpkg 1.18.25
I: Retrieving e2fslibs 1.43.4-2+deb9u1
I: Validating e2fslibs 1.43.4-2+deb9u1
I: Retrieving e2fsprogs 1.43.4-2+deb9u1
I: Validating e2fsprogs 1.43.4-2+deb9u1
I: Retrieving libcomerr2 1.43.4-2+deb9u1
I: Validating libcomerr2 1.43.4-2+deb9u1
I: Retrieving libss2 1.43.4-2+deb9u1
I: Validating libss2 1.43.4-2+deb9u1
I: Retrieving findutils 4.6.0+git+20161106-2
I: Validating findutils 4.6.0+git+20161106-2
I: Retrieving gcc-6-base 6.3.0-18+deb9u1
I: Validating gcc-6-base 6.3.0-18+deb9u1
I: Retrieving libgcc1 1:6.3.0-18+deb9u1
I: Validating libgcc1 1:6.3.0-18+deb9u1
I: Retrieving libstdc++6 6.3.0-18+deb9u1
I: Validating libstdc++6 6.3.0-18+deb9u1
I: Retrieving libc-bin 2.24-11+deb9u4
I: Validating libc-bin 2.24-11+deb9u4
I: Retrieving libc6 2.24-11+deb9u4
I: Validating libc6 2.24-11+deb9u4
I: Retrieving multiarch-support 2.24-11+deb9u4
I: Validating multiarch-support 2.24-11+deb9u4
I: Retrieving gpgv 2.1.18-8~deb9u4
I: Validating gpgv 2.1.18-8~deb9u4
I: Retrieving grep 2.27-2
I: Validating grep 2.27-2
I: Retrieving gzip 1.6-5+b1
I: Validating gzip 1.6-5+b1
I: Retrieving hostname 3.18+b1
I: Validating hostname 3.18+b1
I: Retrieving init-system-helpers 1.48
I: Validating init-system-helpers 1.48
I: Retrieving libcap-ng0 0.7.7-3+b1
I: Validating libcap-ng0 0.7.7-3+b1
I: Retrieving libgcrypt20 1.7.6-2+deb9u3
I: Validating libgcrypt20 1.7.6-2+deb9u3
I: Retrieving libgpg-error0 1.26-2
I: Validating libgpg-error0 1.26-2
I: Retrieving libselinux1 2.6-3+b3
I: Validating libselinux1 2.6-3+b3
I: Retrieving libsemanage-common 2.6-2
I: Validating libsemanage-common 2.6-2
I: Retrieving libsemanage1 2.6-2
I: Validating libsemanage1 2.6-2
I: Retrieving libsepol1 2.6-2
I: Validating libsepol1 2.6-2
I: Retrieving lsb-base 9.20161125
I: Validating lsb-base 9.20161125
I: Retrieving liblz4-1 0.0~r131-2+b1
I: Validating liblz4-1 0.0~r131-2+b1
I: Retrieving mawk 1.3.3-17+b3
I: Validating mawk 1.3.3-17+b3
I: Retrieving libncursesw5 6.0+20161126-1+deb9u2
I: Validating libncursesw5 6.0+20161126-1+deb9u2
I: Retrieving libtinfo5 6.0+20161126-1+deb9u2
I: Validating libtinfo5 6.0+20161126-1+deb9u2
I: Retrieving ncurses-base 6.0+20161126-1+deb9u2
I: Validating ncurses-base 6.0+20161126-1+deb9u2
I: Retrieving ncurses-bin 6.0+20161126-1+deb9u2
I: Validating ncurses-bin 6.0+20161126-1+deb9u2
I: Retrieving libpam-modules 1.1.8-3.6
I: Validating libpam-modules 1.1.8-3.6
I: Retrieving libpam-modules-bin 1.1.8-3.6
I: Validating libpam-modules-bin 1.1.8-3.6
I: Retrieving libpam-runtime 1.1.8-3.6
I: Validating libpam-runtime 1.1.8-3.6
I: Retrieving libpam0g 1.1.8-3.6
I: Validating libpam0g 1.1.8-3.6
I: Retrieving libpcre3 2:8.39-3
I: Validating libpcre3 2:8.39-3
I: Retrieving perl-base 5.24.1-3+deb9u7
I: Validating perl-base 5.24.1-3+deb9u7
I: Retrieving sed 4.4-1
I: Validating sed 4.4-1
I: Retrieving sensible-utils 0.0.9+deb9u1
I: Validating sensible-utils 0.0.9+deb9u1
I: Retrieving login 1:4.4-4.1
I: Validating login 1:4.4-4.1
I: Retrieving passwd 1:4.4-4.1
I: Validating passwd 1:4.4-4.1
I: Retrieving libsystemd0 232-25+deb9u12
I: Validating libsystemd0 232-25+deb9u12
I: Retrieving libudev1 232-25+deb9u12
I: Validating libudev1 232-25+deb9u12
I: Retrieving sysvinit-utils 2.88dsf-59.9
I: Validating sysvinit-utils 2.88dsf-59.9
I: Retrieving tar 1.29b-1.1
I: Validating tar 1.29b-1.1
I: Retrieving tzdata 2020a-0+deb9u1
I: Validating tzdata 2020a-0+deb9u1
I: Retrieving libustr-1.0-1 1.0.4-6
I: Validating libustr-1.0-1 1.0.4-6
I: Retrieving bsdutils 1:2.29.2-1+deb9u1
I: Validating bsdutils 1:2.29.2-1+deb9u1
I: Retrieving libblkid1 2.29.2-1+deb9u1
I: Validating libblkid1 2.29.2-1+deb9u1
I: Retrieving libfdisk1 2.29.2-1+deb9u1
I: Validating libfdisk1 2.29.2-1+deb9u1
I: Retrieving libmount1 2.29.2-1+deb9u1
I: Validating libmount1 2.29.2-1+deb9u1
I: Retrieving libsmartcols1 2.29.2-1+deb9u1
I: Validating libsmartcols1 2.29.2-1+deb9u1
I: Retrieving libuuid1 2.29.2-1+deb9u1
I: Validating libuuid1 2.29.2-1+deb9u1
I: Retrieving mount 2.29.2-1+deb9u1
I: Validating mount 2.29.2-1+deb9u1
I: Retrieving util-linux 2.29.2-1+deb9u1
I: Validating util-linux 2.29.2-1+deb9u1
I: Retrieving liblzma5 5.2.2-1.2+b1
I: Validating liblzma5 5.2.2-1.2+b1
I: Retrieving zlib1g 1:1.2.8.dfsg-5
I: Validating zlib1g 1:1.2.8.dfsg-5
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting libacl1...
I: Extracting libattr1...
I: Extracting libaudit-common...
I: Extracting libaudit1...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting libbz2-1.0...
I: Extracting libdebconfclient0...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting libdb5.3...
I: Extracting debconf...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting libcomerr2...
I: Extracting libss2...
I: Extracting findutils...
I: Extracting gcc-6-base...
I: Extracting libgcc1...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting multiarch-support...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting init-system-helpers...
I: Extracting libcap-ng0...
I: Extracting libgcrypt20...
I: Extracting libgpg-error0...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting lsb-base...
I: Extracting liblz4-1...
I: Extracting mawk...
I: Extracting libncursesw5...
I: Extracting libtinfo5...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting libpcre3...
I: Extracting perl-base...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting login...
I: Extracting passwd...
I: Extracting libsystemd0...
I: Extracting libudev1...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting libustr-1.0-1...
I: Extracting bsdutils...
I: Extracting libblkid1...
I: Extracting libfdisk1...
I: Extracting libmount1...
I: Extracting libsmartcols1...
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting zlib1g...
I: Installing core packages...
I: Unpacking required packages...
I: Unpacking libacl1:amd64...
I: Unpacking libattr1:amd64...
I: Unpacking libaudit-common...
I: Unpacking libaudit1:amd64...
I: Unpacking base-files...
I: Unpacking base-passwd...
I: Unpacking bash...
I: Unpacking libbz2-1.0:amd64...
I: Unpacking libdebconfclient0:amd64...
I: Unpacking coreutils...

I: Unpacking dash...
I: Unpacking libdb5.3:amd64...
I: Unpacking debconf...
I: Unpacking debianutils...
I: Unpacking diffutils...
I: Unpacking dpkg...
I: Unpacking e2fslibs:amd64...
I: Unpacking e2fsprogs...
I: Unpacking libcomerr2:amd64...
I: Unpacking libss2:amd64...
I: Unpacking findutils...
I: Unpacking gcc-6-base:amd64...
I: Unpacking libgcc1:amd64...
I: Unpacking libc-bin...
I: Unpacking libc6:amd64...
I: Unpacking multiarch-support...
I: Unpacking grep...
I: Unpacking gzip...
I: Unpacking hostname...
I: Unpacking init-system-helpers...
I: Unpacking libcap-ng0:amd64...
I: Unpacking libgcrypt20:amd64...
I: Unpacking libgpg-error0:amd64...
I: Unpacking libselinux1:amd64...
I: Unpacking libsemanage-common...
I: Unpacking libsemanage1:amd64...
I: Unpacking libsepol1:amd64...
I: Unpacking lsb-base...
I: Unpacking liblz4-1:amd64...
I: Unpacking mawk...
I: Unpacking libncursesw5:amd64...
I: Unpacking libtinfo5:amd64...
I: Unpacking ncurses-base...
I: Unpacking ncurses-bin...
I: Unpacking libpam-modules:amd64...
I: Unpacking libpam-modules-bin...
I: Unpacking libpam-runtime...
I: Unpacking libpam0g:amd64...
I: Unpacking libpcre3:amd64...
I: Unpacking perl-base...
I: Unpacking sed...
I: Unpacking sensible-utils...
I: Unpacking login...
I: Unpacking passwd...
I: Unpacking libsystemd0:amd64...
I: Unpacking libudev1:amd64...
I: Unpacking sysvinit-utils...
I: Unpacking tar...
I: Unpacking tzdata...
I: Unpacking libustr-1.0-1:amd64...
I: Unpacking bsdutils...
I: Unpacking libblkid1:amd64...
I: Unpacking libfdisk1:amd64...
I: Unpacking libmount1:amd64...
I: Unpacking libsmartcols1:amd64...
I: Unpacking libuuid1:amd64...
I: Unpacking mount...
I: Unpacking util-linux...
I: Unpacking liblzma5:amd64...
I: Unpacking zlib1g:amd64...
I: Configuring required packages...
I: Configuring gcc-6-base:amd64...
I: Configuring lsb-base...
I: Configuring sensible-utils...
I: Configuring ncurses-base...
I: Configuring libsemanage-common...
I: Configuring libaudit-common...
I: Configuring libc6:amd64...
I: Configuring libbz2-1.0:amd64...
I: Configuring libgpg-error0:amd64...
I: Configuring libc-bin...
I: Configuring libdebconfclient0:amd64...
I: Configuring diffutils...
I: Configuring libcomerr2:amd64...
I: Configuring libcap-ng0:amd64...
I: Configuring libsepol1:amd64...
I: Configuring libgcc1:amd64...
I: Configuring libustr-1.0-1:amd64...
I: Configuring libsmartcols1:amd64...
I: Configuring libaudit1:amd64...
I: Configuring libtinfo5:amd64...
I: Configuring libudev1:amd64...
I: Configuring libattr1:amd64...
I: Configuring libss2:amd64...
I: Configuring liblzma5:amd64...
I: Configuring base-passwd...
I: Configuring e2fslibs:amd64...
I: Configuring liblz4-1:amd64...
I: Configuring debianutils...
I: Configuring libgcrypt20:amd64...
I: Configuring libncursesw5:amd64...
I: Configuring libdb5.3:amd64...
I: Configuring zlib1g:amd64...
I: Configuring hostname...
I: Configuring multiarch-support...
I: Configuring mawk...
I: Configuring libpcre3:amd64...
I: Configuring base-files...
I: Configuring libselinux1:amd64...
I: Configuring findutils...
I: Configuring libacl1:amd64...
I: Configuring ncurses-bin...
I: Configuring sed...
I: Configuring libsystemd0:amd64...
I: Configuring coreutils...
I: Configuring tar...
I: Configuring libsemanage1:amd64...
I: Configuring dpkg...
I: Configuring perl-base...
I: Configuring grep...
I: Configuring debconf...
I: Configuring tzdata...
I: Configuring gzip...
I: Configuring bsdutils...
I: Configuring dash...
I: Configuring init-system-helpers...
I: Configuring libpam0g:amd64...
I: Configuring libpam-modules-bin...
I: Configuring bash...
I: Configuring libpam-modules:amd64...
I: Configuring libpam-runtime...
I: Configuring passwd...
I: Configuring login...
I: Configuring libuuid1:amd64...
I: Configuring libblkid1:amd64...
I: Configuring libmount1:amd64...
I: Configuring mount...
I: Configuring libfdisk1:amd64...
I: Configuring util-linux...
I: Configuring e2fsprogs...
I: Configuring sysvinit-utils...
I: Configuring libc-bin...
I: Unpacking the base system...
I: Unpacking adduser...
I: Unpacking apt...
I: Unpacking libapt-pkg5.0:amd64...
I: Unpacking debian-archive-keyring...
I: Unpacking libstdc++6:amd64...
I: Unpacking gpgv...
I: Configuring the base system...
I: Configuring gpgv...
I: Configuring debian-archive-keyring...
I: Configuring libstdc++6:amd64...
I: Configuring adduser...
I: Configuring libapt-pkg5.0:amd64...
I: Configuring apt...
I: Configuring libc-bin...
I: Base system installed successfully.
warning: no apparent 'stretch/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch/main' ...
warning: no apparent 'stretch-security/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian-security/20210701T143549Z
skipping 'stretch-security/main' ...
warning: no apparent 'stretch-updates/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch-updates/main' ...
error: sources.list ended up empty -- something is definitely wrong
The command '/bin/sh -c debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"' returned a non-zero code: 1
```

**Comment by tianon** [comment] 2021-07-02 17:29
That's really strange; I can't reproduce: :confused:

```console
$ ./docker-run.sh --pull
...
Successfully tagged debuerreotype/debuerreotype:0.13-dev
root@debuerreotype:/workdir# debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
I: Valid Release signature (key id 067E3C456BAE240ACEE88F6FEF0F382A1A7B6500)
I: Retrieving Packages 
I: Validating Packages 
...
I: Configuring apt...
I: Configuring libc-bin...
I: Base system installed successfully.
root@debuerreotype:/workdir# 
```

**Comment by andrewzah** [comment] 2021-07-02 17:57
It seems to be some diff then between my dockerfile and your dockerfile.

```
FROM debian:buster-slim as rootfs-stage

ARG DEBUERREOTYPE_VERSION="0.12"

RUN apt update -y \
  && apt install -y \
    bash \
    ca-certificates \
    curl \
    debootstrap \
    dirmngr \
    git \
    gnupg \
    wget \
    xz-utils \
  && rm -rf /var/lib/apt/lists/*

RUN set -eux \
  && wget \
    -O distro-info-data.deb 'http://snapshot.debian.org/archive/debian/20210130T024253Z/pool/main/d/distro-info-data/distro-info-data_0.46_all.deb' \
  && echo '9f06132ddd508802ee0272ecac8b1f301426ffea *distro-info-data.deb' | sha1sum --strict --check - \
  && apt-get install -y \
    ./distro-info-data.deb \
  && rm distro-info-data.deb \
  && [ -s /usr/share/distro-info/debian.csv ]

WORKDIR /opt
RUN git clone "https://github.com/debuerreotype/debuerreotype.git" \
  && cd debuerreotype \
  && git checkout "$DEBUERREOTYPE_VERSION" \
  && chmod +x ./scripts/*

# remove unshare() call
COPY ./debuerreotype-chroot /opt/debuerreotype/scripts/debuerreotype-chroot

WORKDIR /opt/debuerreotype/scripts
RUN for f in debuerreotype-*; do \
    ln -svL "$PWD/$f" "/usr/local/bin/$f"; \
  done
```
I had to modify it because if I have a run step in a docker image with `debuerreotype-init...` it fails with the following:

```
I: Base system installed successfully.
unshare: unshare failed: Operation not permitted
```

**Comment by andrewzah** [comment] 2021-07-06 14:47
@tianon is there a way to get around this `unshare` issue? I'm unfamiliar with it.

**Comment by tianon** [comment] 2021-07-06 21:14
Running `unshare` is a privileged operation (it's essentially creating a container, which as you've discovered isn't allowed in containers by default).  The way I run these scripts is intentionally such that it creates a "proper" chroot using `unshare` to be able to actually mount `/proc`, `/dev`, etc.  I have done some experiments without (and indeed, `debootstrap` is supposed to support working without doing so, as you're taking advantage of), but I haven't devoted much time to that.

However, I do not think that's likely to be related to your issues downloading files unless something really bizarre is happening.  If you run the script with `bash -x` you can get a (very verbose) trace of every instruction that gets invoked so you can see the full URLs it attempts to download and then try replicating just those `wget` commands directly with more verbosity to see if you can get additional clues.

**Comment by andrewzah** [comment] 2021-07-07 15:41
Can you replicate this with a docker build?

```dockerfile
FROM debuerreotype/debuerreotype:latest

WORKDIR /

RUN bash -x debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
```
```bash
$ docker build . -t "debuerreotype-test"

...
I: Base system installed successfully.
+ echo 1625150149
+ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -z '' ']'
+ /opt/debuerreotype/scripts/debuerreotype-debian-sources-list --snapshot /rootfs stretch
unshare: unshare failed: Operation not permitted
```
---
```dockerfile
# with unshare() commented out in debuerreotype-chroot
FROM andrewzah/debian-debuerreotype:2021-07-07 as rootfs

WORKDIR /

RUN bash -x debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
```
```bash
$ docker build . -t "debuerreotype-test"

...
I: Base system installed successfully.
+ echo 1625150149
+ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -z '' ']'
+ /opt/debuerreotype/scripts/debuerreotype-debian-sources-list --snapshot /rootfs stretch
warning: no apparent 'stretch/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch/main' ...
warning: no apparent 'stretch-security/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian-security/20210701T143549Z
skipping 'stretch-security/main' ...
warning: no apparent 'stretch-updates/main' for '' on any of the following
  - http://snapshot.debian.org/archive/debian/20210701T143549Z
skipping 'stretch-updates/main' ...
error: sources.list ended up empty -- something is definitely wrong

```

**Comment by tianon** [comment] 2021-07-07 16:57
It definitely will have edge cases where it is not sufficient, but I was able to successfully run this via the following:

```dockerfile
FROM debuerreotype/debuerreotype

RUN set -eux; \
	chroot="$(which chroot)"; \
	debuerreotype="$(which debuerreotype-chroot)"; \
	debuerreotype="$(readlink -ve "$debuerreotype")"; \
	ln -svfT "$chroot" "$debuerreotype"

RUN debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
```

```console
$ docker build .
Sending build context to Docker daemon  34.82kB
Step 1/3 : FROM debuerreotype/debuerreotype
 ---> b09cafb5379f
Step 2/3 : RUN set -eux; 	chroot="$(which chroot)"; 	debuerreotype="$(which debuerreotype-chroot)"; 	debuerreotype="$(readlink -ve "$debuerreotype")"; 	ln -svfT "$chroot" "$debuerreotype"
 ---> Running in 2aafe12bbaa9
+ which chroot
+ chroot=/usr/sbin/chroot
+ which debuerreotype-chroot
+ debuerreotype=/usr/local/bin/debuerreotype-chroot
+ readlink -ve /usr/local/bin/debuerreotype-chroot
+ debuerreotype=/opt/debuerreotype/scripts/debuerreotype-chroot
+ ln -svfT /usr/sbin/chroot /opt/debuerreotype/scripts/debuerreotype-chroot
'/opt/debuerreotype/scripts/debuerreotype-chroot' -> '/usr/sbin/chroot'
Removing intermediate container 2aafe12bbaa9
 ---> 76d2ff5a528b
Step 3/3 : RUN debuerreotype-init /rootfs stretch "2021-07-01T14:35:49Z"
 ---> Running in ac136442331a
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
I: Valid Release signature (key id 067E3C456BAE240ACEE88F6FEF0F382A1A7B6500)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Checking component main on http://snapshot.debian.org/archive/debian/20210701T143549Z...
...
I: Extracting zlib1g...
W: Failure trying to run: chroot "/rootfs" mount -t proc proc /proc
W: See /rootfs/debootstrap/debootstrap.log for details
W: Failure trying to run: chroot "/rootfs" mount -t sysfs sysfs /sys
W: See /rootfs/debootstrap/debootstrap.log for details
I: Installing core packages...
...
I: Configuring apt...
I: Configuring libc-bin...
I: Base system installed successfully.
Removing intermediate container ac136442331a
 ---> 6f7b6d845398
Successfully built 6f7b6d845398
```

**Comment by tianon** [comment] 2021-07-31 00:30
Since I can't reproduce the 404, I'm going to close this, but I've opened #118 to track making the usage of `unshare` (and thus also `mount`) optional.

**Closed by tianon** 2021-07-31 00:30 UTC
