### ISSUE TITLE
Install error of openjdk with debian:10-slim

### ISSUE THREAD

**Issue by Zlika** [debuerreotype/debuerreotype#106] opened 2021-03-14 10:14 UTC
Hi!
I don't know if it's the right place to report this problem, but openjdk-11-jre-headless cannot be installed with the debian:10-slim docker image.

Dockerfile:
```
FROM debian:10-slim
RUN apt-get update && apt-get install -y openjdk-11-jre-headless
```

Output:
```
...
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:UCA_Global_G2_Root.pem
Adding debian:Entrust_Root_Certification_Authority.pem
done.
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for ca-certificates (20200601~deb10u2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-11-jre-headless:amd64 (11.0.9.1+1-1~deb10u2) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rmid.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):
 installed openjdk-11-jre-headless:amd64 package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 openjdk-11-jre-headless:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && apt-get install -y openjdk-11-jre-headless' returned a non-zero code: 100
```

**Comment by tianon** [comment] 2021-03-18 01:34
Looks like a duplicate of https://github.com/debuerreotype/debuerreotype/issues/10 😅

**Closed** 2021-03-28 02:51 UTC
